### ISSUE TITLE
[cetic/microservice] Isn't bad practice to set resource limits?

### ISSUE THREAD

**Issue by Nico-Salamone** [cetic/helm-microservice#2]
Currently, in [values.yaml](https://github.com/cetic/helm-microservice/blob/master/values.yaml) file, resource limits are set. Isn't this a bad practice in Kubernetes?

**Is your feature request related to a problem? Please describe.**
By default, pods can only use 2 CPUs and 2 GB of memory. If a user of this chart doesn't notice this, they might wonder why a particular pod is "slow".

**Describe the solution you'd like**
In the `values.yaml` file, replace this:

```yaml
resources:
  limits:
    cpu: 2
    memory: 2000Mi
  requests:
    cpu: 500m
    memory: 500Mi
```

by this:

```yaml
resources:
  requests:
    cpu: 500m
    memory: 500Mi
```
